name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@master
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
